<?= $this->extend('admin/layout/template'); ?>
<?= $this->section('content'); ?>
<div class="app-content-header"><div class="container-fluid d-flex justify-content-between align-items-center"><div><h3 class="mb-1">Kartu Lima Nilai Utama</h3><small class="text-muted">Kelola isi kartu yang tampil pada section Nilai di homepage.</small></div><a href="<?= base_url('admin/about-values/create'); ?>" class="btn btn-primary"><i class="fas fa-plus me-1"></i> Tambah Kartu</a></div></div>
<div class="app-content"><div class="container-fluid">
<?php foreach (['success' => 'success', 'error' => 'danger'] as $key => $type): if (session()->getFlashdata($key)): ?><div class="alert alert-<?= $type; ?>"><?= esc(session()->getFlashdata($key)); ?></div><?php endif; endforeach; ?>
<div class="card card-outline card-primary"><div class="card-body table-responsive"><table class="table table-hover align-middle"><thead class="table-light"><tr><th style="width:70px">Urutan</th><th>Nilai (ID)</th><th>English</th><th>Deskripsi</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
<?php foreach ($values as $value): ?><tr><td><?= (int) $value['sort_order']; ?></td><td><strong><?= esc($value['label']); ?></strong></td><td><?= !empty($value['label_en']) ? esc($value['label_en']) : '<span class="text-danger">Belum diterjemahkan</span>'; ?></td><td><small><?= esc(mb_strimwidth((string) ($value['description'] ?? ''), 0, 100, '...')); ?></small></td><td><?= !empty($value['published']) ? '<span class="badge text-bg-success">Tampil</span>' : '<span class="badge text-bg-secondary">Hidden</span>'; ?></td><td><a href="<?= base_url('admin/about-values/edit/' . $value['id']); ?>" class="btn btn-sm btn-warning"><i class="fas fa-edit"></i></a><form action="<?= site_url('admin/about-values/delete/' . $value['id']); ?>" method="post" class="d-inline" onsubmit="return confirm('Hapus kartu ini?')"><?= csrf_field(); ?><button class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button></form></td></tr><?php endforeach; ?>
<?php if (!$values): ?><tr><td colspan="6" class="text-center text-muted">Belum ada kartu nilai.</td></tr><?php endif; ?></tbody></table></div></div>
</div></div>
<?= $this->endSection(); ?>
